const blankLine = '  |   |  ';
const msgEmpty = 'This is what an empty board would look like: ';
const msgGuessBomb = 'This is what a board with a guess and a bomb on it would look like: ';
const guessLine = '1 |   |  ';
const bombLine = '  | B |  ';
console.log(msgEmpty);
console.log(blankLine);
console.log(blankLine);
console.log(blankLine);
console.log(msgGuessBomb);
console.log(guessLine);
console.log(bombLine);
console.log(blankLine);